version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_policy_manager_service
      POSTGRES_PASSWORD: Ramon2020!
      POSTGRES_DB: db_policy_manager_service
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --aclfile /usr/local/etc/redis/users.acl
    volumes:
      - redis-data:/data
      - ./redis/users.acl:/usr/local/etc/redis/users.acl
    healthcheck:
      test: [ "CMD", "redis-cli", "-u", "redis://policy_user:policy_pass@localhost:6379", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: mysql:8.0
    container_name: keycloak-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
    volumes:
      - keycloak-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-db:3306/keycloak_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  db-data: {}
  redis-data: {}
  keycloak-db-data: {}
  keycloak-data: {}
