apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

# Patch para aumentar o número de réplicas e recursos em PROD
patches:
  - target:
      kind: Deployment
      name: policy-management-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

images:
  - name: alysongustavo/policy-management-service
    newTag: stable