apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-management-ingress
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123456789:certificate/SUA-CHAVE-DEV
spec:
  rules:
    - host: api-dev.desafiochomadev.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: policy-management-service-dev
                port:
                  number: 80